<?php
if (!defined('ABSPATH')) exit;
class Bitey_API {
 private $allowed_extensions=array('pdf','doc','docx','txt','csv','json','md');
 public function __construct(){foreach(array('wp_ajax_bitey_send_message','wp_ajax_nopriv_bitey_send_message','wp_ajax_bitey_chat','wp_ajax_nopriv_bitey_chat') as $a)add_action($a,array($this,'send_message'));add_action('wp_ajax_bitey_import_company',array($this,'import_company'));add_action('wp_ajax_nopriv_bitey_import_company',array($this,'import_company'));add_action('rest_api_init',array($this,'register_rest_routes'));}
 public function register_rest_routes(){register_rest_route('bitey/v1','/chat',array('methods'=>'POST','permission_callback'=>array($this,'rest_permission'),'callback'=>array($this,'rest_chat')));}
 public function rest_permission(WP_REST_Request $r){$n=$r->get_header('X-WP-Nonce');return $n&&wp_verify_nonce($n,'wp_rest');}
 private function lang($v){$v=strtolower(trim((string)$v));return array('auto'=>'auto','pt'=>'pt-BR','pt-br'=>'pt-BR','es'=>'es','en'=>'en')[$v]??'auto';}
 private function fail($c,$r,$s=502){wp_send_json_error(array('code'=>$c,'reply'=>$r),$s);}
 private function request_data($s){$ref=wp_get_raw_referer();$url=isset($s['page_url'])?esc_url_raw(wp_unslash($s['page_url'])):$ref;$title=isset($s['page_title'])?sanitize_text_field(wp_unslash($s['page_title'])):wp_get_document_title();$hint=isset($s['service_hint'])?sanitize_key(wp_unslash($s['service_hint'])):'';if(!$hint){$x=strtolower($url.' '.$title);if(preg_match('/cctv|camara|c[aá]maras|seguridad/',$x))$hint='cctv_installation';elseif(preg_match('/red|wifi|wi-fi/',$x))$hint='network_configuration';elseif(preg_match('/notebook|computador|computer|pc/',$x))$hint='computer_repair';elseif(preg_match('/celular|movil|m[oó]vil|smartphone/',$x))$hint='mobile_phone_repair';}return array('message'=>sanitize_textarea_field(wp_unslash($s['message']??'')),'name'=>sanitize_text_field(wp_unslash($s['name']??'')),'last_name'=>sanitize_text_field(wp_unslash($s['last_name']??'')),'phone'=>sanitize_text_field(wp_unslash($s['phone']??'')),'email'=>sanitize_email(wp_unslash($s['email']??'')),'company_id'=>absint($s['company_id']??1)?:1,'channel'=>sanitize_key(wp_unslash($s['channel']??'website')),'conversation_id'=>sanitize_key(wp_unslash($s['conversation_id']??'')),'language_preference'=>$this->lang($s['language_preference']??'auto'),'preferred_contact_channel'=>sanitize_key(wp_unslash($s['preferred_contact_channel']??'')),'page_context'=>array('url'=>$url,'title'=>$title,'service_hint'=>$hint),'service_context'=>array('company_id'=>absint($s['company_id']??1)?:1,'business_role'=>'service_provider'));}
 private function backend(){return untrailingslashit((string)get_option('bitey_backend_url','https://bitefixes-backend.onrender.com'));}
 private function parse($r){if(is_wp_error($r))return $r;$s=wp_remote_retrieve_response_code($r);$b=json_decode(wp_remote_retrieve_body($r),true);if($s<200||$s>=300)return new WP_Error('backend_http_error','Bitey Backend devolvió un error HTTP.',array('status'=>$s));if(!is_array($b))return new WP_Error('invalid_backend_json','Respuesta inválida.');return $b;}
 private function call($d){if($d['message']==='')return new WP_Error('empty_message','Escribe un mensaje para continuar.');$p=array('message'=>$d['message'],'phone'=>$d['phone'],'email'=>$d['email'],'company_id'=>$d['company_id'],'customer_name'=>trim($d['name'].' '.$d['last_name'])?:'Customer','channel'=>$d['channel'],'conversation_id'=>$d['conversation_id'],'language_preference'=>$d['language_preference'],'preferred_contact_channel'=>$d['preferred_contact_channel'],'page_context'=>$d['page_context'],'service_context'=>$d['service_context']);$r=wp_remote_post($this->backend().'/chat',array('timeout'=>30,'headers'=>array('Accept'=>'application/json','Content-Type'=>'application/json'),'body'=>wp_json_encode($p)));$b=$this->parse($r);if(is_wp_error($b))return $b;$reply=$b['response']??$b['reply']??$b['message']??'';if(is_array($reply))$reply=$reply['text']??$reply['message']??'';if($reply==='')return new WP_Error('empty_backend_response','Bitey no devolvió una respuesta.');return array('reply'=>wp_kses_post((string)$reply),'intent'=>$b['intent']??null,'confidence'=>$b['confidence']??null,'ticket_id'=>$b['ticket_id']??null,'customer_id'=>$b['customer_id']??null,'customer_name'=>$b['customer_name']??($d['name']?:null),'language'=>$b['language']??null,'language_source'=>$b['language_source']??null,'conversation_id'=>$b['conversation_id']??$d['conversation_id'],'knowledge_found'=>$b['knowledge_found']??false,'memory'=>$b['memory']??null,'ai_consultation'=>$b['ai_consultation']??array(),'learning_events'=>$b['learning_events']??array(),'bitey_context'=>$b['bitey_context']??array(),'comparative_evaluation'=>$b['comparative_evaluation']??null,'response_source'=>$b['response_source']??'core');}
 public function rest_chat(WP_REST_Request $r){$x=$this->call($this->request_data($r->get_json_params()?:array()));if(is_wp_error($x))return new WP_REST_Response(array('success'=>false,'data'=>array('code'=>$x->get_error_code(),'reply'=>$x->get_error_message())),$x->get_error_code()==='empty_message'?400:502);return new WP_REST_Response(array('success'=>true,'data'=>$x),200);}
 private function validate_upload($f){if(empty($f)||$f['error']!==UPLOAD_ERR_OK)return new WP_Error('file_upload_error','No se pudo recibir el documento.');if($f['size']>10*1024*1024)return new WP_Error('file_too_large','El documento supera 10 MB.');$n=sanitize_file_name($f['name']);$e=strtolower(pathinfo($n,PATHINFO_EXTENSION));if(!in_array($e,$this->allowed_extensions,true))return new WP_Error('file_type_not_allowed','Tipo de documento no permitido.');return array('name'=>$n,'type'=>sanitize_text_field($f['type']??'application/octet-stream'),'data'=>file_get_contents($f['tmp_name']));}
 public function import_company(){if(!check_ajax_referer('bitey_nonce','nonce',false))$this->fail('invalid_nonce','Solicitud no autorizada.',403);$f=$this->validate_upload($_FILES['company_document']??null);if(is_wp_error($f))$this->fail($f->get_error_code(),$f->get_error_message(),400);$boundary='----Bitey'.wp_generate_password(16,false,false);$body='';foreach(array('company_id'=>absint($_POST['company_id']??1),'company_name'=>sanitize_text_field(wp_unslash($_POST['company_name']??'')),'source'=>'wordpress_globe','channel'=>'website') as $k=>$v)$body.="--$boundary\r\nContent-Disposition: form-data; name=\"$k\"\r\n\r\n$v\r\n";$body.="--$boundary\r\nContent-Disposition: form-data; name=\"file\"; filename=\"{$f['name']}\"\r\nContent-Type: {$f['type']}\r\n\r\n{$f['data']}\r\n--$boundary--\r\n";$r=wp_remote_post($this->backend().'/company-profile/import',array('timeout'=>60,'headers'=>array('Content-Type'=>'multipart/form-data; boundary='.$boundary),'body'=>$body));$b=$this->parse($r);if(is_wp_error($b))$this->fail($b->get_error_code(),$b->get_error_message(),502);wp_send_json_success($b);}
 public function send_message(){if(!check_ajax_referer('bitey_nonce','nonce',false))$this->fail('invalid_nonce','Solicitud no autorizada.',403);$x=$this->call($this->request_data($_POST));if(is_wp_error($x))$this->fail($x->get_error_code(),$x->get_error_message(),502);wp_send_json_success($x);}
}